# -*- coding: utf-8 -*-

import os
import sys
from pathlib import Path

import click


if __name__ == "__main__":
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import yaml

import wireviz.wireviz as wv
from wireviz import APP_NAME, __version__
from wireviz.wv_bom import bom_list
from wireviz.wv_output import generate_pdf_output, generate_html_output, generate_shared_bom
from wireviz.wv_dataclasses import AUTOGENERATED_PREFIX, Metadata, Options

format_codes = {
    "c": "csv",
    "g": "gv",
    "h": "html",
    "p": "png",
    "P": "pdf",
    "s": "svg",
    "t": "tsv",
    "b": "shared_bom",
}

epilog = (
    "The -f or --formats option accepts a string containing one or more of the "
    "following characters to specify which file types to output:\n"
    + f", ".join([f"{key} ({value.upper()})" for key, value in format_codes.items()])
)


@click.command(epilog=epilog, no_args_is_help=True)
@click.argument(
    "files",
    type=click.Path(
        exists=True,
        readable=True,
        dir_okay=False,
        path_type=Path,
    ),
    nargs=-1,
    required=True,
)
@click.option(
    "-f",
    "--formats",
    default="hpst",
    type=str,
    show_default=True,
    help="Output formats (see below).",
)
@click.option(
    "-p",
    "--prepend",
    default=[],
    multiple=True,
    type=click.Path(
        exists=True,
        readable=True,
        file_okay=True,
        path_type=Path,
    ),
    help="YAML file to prepend to the input file (optional).",
)
@click.option(
    "-o",
    "--output-dir",
    default=None,
    type=click.Path(
        exists=True,
        readable=True,
        file_okay=False,
        dir_okay=True,
        path_type=Path,
    ),
    help="Directory to use for output files, if different from input file directory.",
)
@click.option(
    "-O",
    "--output-name",
    default=None,
    type=str,
    help=(
        "File name (without extension) to use for output files, "
        "if different from input file name."
    ),
)
@click.option(
    "-V",
    "--version",
    is_flag=True,
    default=False,
    help=f"Output {APP_NAME} version and exit.",
)
@click.option(
    "-u",
    "--use-qty-multipliers",
    is_flag=True,
    type=bool,
    help="if set, the shared bom counts will be scaled with the qty-multipliers",
)
@click.option(
    "-m",
    "--multiplier-file-name",
    default='quantity_multipliers.txt',
    type=str,
    help="name of file used to fetch the qty_multipliers",
)
def cli(files, formats, prepend, output_dir, output_name, version, use_qty_multipliers, multiplier_file_name):
    """
    Parses the provided FILE and generates the specified outputs.
    """
    if version:
        print(f"{APP_NAME} {__version__}")
        return  # print version number only and exit

    _output_dir = files[0].parent if not output_dir else output_dir

    # determine output formats
    output_formats = {format_codes[f] for f in formats if f in format_codes}
    harness_output_formats = output_formats.copy()
    create_titlepage = False
    # Only generate the global pdf if there's multiple files
    if len(files) > 1 and 'pdf' in harness_output_formats:
        harness_output_formats.remove('pdf')
        create_titlepage = True
        titlepage_path = (_output_dir / "titlepage").with_suffix(".html")

    harness = None
    shared_bom = {}
    sheet_current = 1
    if create_titlepage:
        sheet_current += 1
    output_names = []
    # run WireVIz on each input file
    for _file in files:
        _output_name = _file.stem if not output_name else output_name
        output_names.append(_output_dir / _output_name)

        print("Input file:  ", _file)
        print(
            "Output file: ",
            f"{_output_dir / _output_name}.[{'|'.join(output_formats)}]",
        )

        extra_metadata = {}
        extra_metadata["sheet_name"] = _output_name.upper()
        extra_metadata["sheet_total"] = len(files)
        if create_titlepage:
            extra_metadata["sheet_total"] += 1
        extra_metadata["sheet_current"] = sheet_current
        sheet_current += 1

        file_dir = _file.parent

        ret = wv.parse(
            prepend + (_file,),
            return_types=("shared_bom"),
            output_formats=harness_output_formats,
            output_dir=_output_dir,
            output_name=_output_name,
            extra_metadata=extra_metadata,
            shared_bom=shared_bom,
        )
        shared_bom = ret["shared_bom"]

    shared_bom_base = None
    if "shared_bom" in output_formats:
        shared_bom_base, shared_bomlist = generate_shared_bom(
            _output_dir,
            shared_bom,
            use_qty_multipliers=use_qty_multipliers,
            files=files,
            multiplier_file_name=multiplier_file_name,
        )

    # TODO: instead have a parse function that create a titlepage, not a harness
    if ('html' in output_formats) and create_titlepage:
        yaml_data_str = "\n".join(f.open("r").read() for f in prepend)
        yaml_data = yaml.safe_load(yaml_data_str)
        titlepage_metadata = {
            **yaml_data.get("metadata", {}),
            **extra_metadata,
            "sheet_current": 1,
            "sheet_name": "titlepage",
            "output_name": "titlepage",
            "bom_updated_position": "top: 20mm; left: 10mm",
            "notes_width": "200mm",
        }
        titlepage_metadata['template']['name'] = 'titlepage'
        titlepage_options = {
            **yaml_data.get("options", {}),
            "show_bom": True,
            "show_notes": True,
        }
        generate_html_output(
            titlepage_path,
            bom = bom_list(shared_bom),
            metadata = Metadata(**titlepage_metadata), # TBD what we need to add here
            options = Options(**titlepage_options),
        )

    if 'pdf' in output_formats and 'html' in output_formats and len(output_names) > 1:
        if create_titlepage:
            output_names.insert(0, titlepage_path)

        generate_pdf_output(output_names)


    print()  # blank line after execution


if __name__ == "__main__":
    cli()
