name: Create Examples

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Install project
        run: uv sync --python ${{ matrix.python-version }}
      - name: Create Examples
        run: uv run --python ${{ matrix.python-version }} python src/wireviz/tools/build_examples.py
      - name: Upload examples, demos, and tutorials
        uses: actions/upload-artifact@v4
        with:
          name: examples-and-tutorials-v${{ matrix.python-version }}
          path: |
            examples/
            tutorial/
          if-no-files-found: error
